### ISSUE TITLE
it will crash in x32dbg, maybe you didn't test well before release.

### ISSUE THREAD

**Issue by cxj98** [ThunderCls/xAnalyzer#5] opened 2016-12-03 15:01 UTC
问题签名:
  问题事件名称:	BEX
  应用程序名:	x32dbg.exe
  应用程序版本:	0.0.2.5
  应用程序时间戳:	584095c2
  故障模块名称:	xAnalyzer.dp32
  故障模块版本:	0.0.0.0
  故障模块时间戳:	583cf68d
  异常偏移:	00006494
  异常代码:	c0000417
  异常数据:	00000000
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	6fe6
  其他信息 2:	6fe607cdfc3455c9c2a2b9fdb8b2fcac
  其他信息 3:	aa4e
  其他信息 4:	aa4e28b4d7c0a2f44c9b912fc3b2a0c3

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by cxj98** [comment] 2016-12-03 15:13
all use last build.

**Comment by ThunderCls** [comment] 2016-12-03 17:37
First of all thanks for reporting. Yes the plugin was tested, maybe not OS widely, but tested indeed applications widely in Windows 10 x64 with the latest releases of x64dbg. I'm gonna need a little more details in order to reproduce the same error, the exe used, also what x64dbg version and even the language used

**Comment by cxj98** [comment] 2016-12-03 19:16
64bit win 7 ultimate, English, Set Interface to Chinese and location to China

load any exe will crash, i use latest build x32dbg with latest build xAnalyzer Plugin, not test in x64dbg.

I found something useful for you, if load only xAnalyzer without other plugins, it will work fine, but if load with other plugins will crash x32dbg debuger.

**Comment by ThunderCls** [comment] 2016-12-03 21:19
Ok I'm not sure what your problem is, apparently I can't reproduce it

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/13303069/20862263/34cb97ca-b974-11e6-87f1-695d543e5ab0.gif)

**Comment by cxj98** [comment] 2016-12-04 00:42
please download this full pack to test.

https://share.weiyun.com/37c5aa26571a2d30a8ac357456faf0f4

**Comment by ThunderCls** [comment] 2016-12-04 04:18
I tested those in the same VM (Windows 7 Ultimate x64) and actually the trouble makers there are:

- x64dbg_tol.dp32
- qt_x64dbg.dp32

If you delete those two you won't get any more crashes and if you delete only xAnalyzer among all the plugins instead of those too, crashes will continue, so there you have it. 
xAnalyzer its safe, those two are not. Even though crash dumps indicated xAnalyzer as the crash reason, sometimes stack/memory corruption make other modules to crash, for this reason you have to take off as many variables as possible when catching a bug, so I did through isolation-trial-error to catch this one...well, just for the records.

**Comment by wk-952** [comment] 2016-12-04 07:29
@ThunderCls I'm having a crash too when I try to analyze some modules.
Try for example analyzing `x32dbg.exe` itself, that always crashes for me.
Another example is `010 Editor`.

Reproduced on Win10 64-bit with latest snapshot of the debugger.
Plugins installed: `Scylla`, `ScyllaHide` (using `Disabled` profile), `OllyDumpEx`, `Multiline assembler`, `xAnalyzer`.

**Comment by cxj98** [comment] 2016-12-04 10:00
x64dbg_tol.dp32 is a unicode string search plugin, there is no reason to delete this one.

**Comment by ThunderCls** [comment] 2016-12-04 21:49
@cxj98 I'm not saying you "have" to delete anything. You reported a crash and I'm just giving you the reason of that crash, nothing else, in my test those two plugins are the ones that make x64dbg crash and not xAnalyzer and that's it.

@wk-952 actually those were a couple BoF going on, thanks for reporting, in the next update those will be fixed :)

**Closed** 2016-12-06 02:48 UTC
Labels: crash, not reproduced

**Comment by wk-952** [comment] 2016-12-06 03:21
Thank you.

**Comment by ThunderCls** [comment] 2016-12-06 04:12
Np @wk-952, thanks to you
